import "./globals.css";
import { Itim, Jaldi } from "next/font/google";
import NavBarBottom from "./components/NavBarBottom/NavBarBottom";
const itim = Itim({ subsets: ["latin"], weight: "400" });
const jaldi = Jaldi({
  subsets: ["latin"],
  weight: ["400", "700"],
});
import NavBarTop from "./components/NavBarTop/NavBarTop";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className=" font-jaldi ">
        <NavBarTop />
        {children}
        <NavBarBottom />
      </body>
    </html>
  );
}
